# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fe9e152266ad591a02bb364ab90140a7df755b20a5c7b1715e5d486f3782a3c9080b301e7ec99093084ca880456c3a37df376c6ec4088ce56c929a979ba0124

test:
  secret_key_base: f4721ff86a9820f8ccada60a5808aa9e8640acca3aa10a1550335ad9f4766f0eeeecbbca11723082471ad769911fc0cd632c788f7cc6bacde99cffe9b2c0405c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
